---
name: Build and push images to Github Container Registry
on:
  push:
    branches:
      - main
jobs:
  push:
    # runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build images
        run: make build

      - name: Push images
        run: make push
